INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('11','Aceh','AC','Banda Aceh','Sumatra');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('12','Sumatra Utara','SU','Medan','Sumatra');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('13','Sumatra Barat','SB','Padang','Sumatra');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('14','Riau','RI','Pekanbaru','Sumatra');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('15','Jambi','JA','Jambi','Sumatra');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('16','Sumatra Selatan','SS','Palembang','Sumatra');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('17','Bengkulu','BE','Bengkulu','Sumatra');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('18','Lampung','LA','Bandar Lampung','Sumatra');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('19','Kepulauan Bangka Belitung','BB','Pangkalpinang','Sumatra');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('21','Kepulauan Riau','KR','Tanjungpinang','Sumatra');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('31','Daerah Khusus Ibukota Jakarta','JK','—[d]','Jawa');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('32','Jawa Barat','JB','Bandung','Jawa');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('33','Jawa Tengah','JT','Semarang','Jawa');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('34','Daerah Istimewa Yogyakarta','YO','Yogyakarta','Jawa');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('35','Jawa Timur','JI','Surabaya','Jawa');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('36','Banten','BT','Serang','Jawa');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('51','Bali','BA','Denpasar','Nusa Tenggara');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('52','Nusa Tenggara Barat','NB','Mataram','Nusa Tenggara');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('53','Nusa Tenggara Timur','NT','Kupang','Nusa Tenggara');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('61','Kalimantan Barat','KB','Pontianak','Kalimantan');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('62','Kalimantan Tengah','KT','Palangka Raya','Kalimantan');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('63','Kalimantan Selatan','KS','Banjarbaru','Kalimantan');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('64','Kalimantan Timur','KI','Samarinda','Kalimantan');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('65','Kalimantan Utara','KU','Tanjung Selor','Kalimantan');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('71','Sulawesi Utara','SA','Manado','Sulawesi');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('72','Sulawesi Tengah','ST','Palu','Sulawesi');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('73','Sulawesi Selatan','SN','Makassar','Sulawesi');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('74','Sulawesi Tenggara','SG','Kendari','Sulawesi');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('75','Gorontalo','GO','Gorontalo','Sulawesi');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('76','Sulawesi Barat','SR','Mamuju','Sulawesi');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('81','Maluku','MA','Ambon','Maluku');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('82','Maluku Utara','MU','Sofifi','Maluku');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('91','Papua','PA','Jayapura','Papua');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('92','Papua Barat','PB','Manokwari','Papua');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('93','Papua Selatan','PS','Salor','Papua');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('94','Papua Tengah','PT','Wanggar','Papua');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('95','Papua Pegunungan','PE','Jayawijaya','Papua');
INSERT INTO "provinsi" (kode, nama, iso, ibukota, geografi) VALUES('96','Papua Barat Daya','PD','Sorong','Papua');
